import type { Article } from "@/migration/types"

const articlesList: Article[] = [
  {
    href: "https://twitter.com/i/spaces/1lPKqBMQVedGb?s=20",
    title:
      "[Speaker] 'Should Front-End Developers know Back-End Technologies?' by @zlatov_cristina",
    tags: [
      "EN",
      "Panel Discussion",
      "Speaker",
      "Spaghetti Spaces",
      "X (Twitter)",
      "Web Development",
      "Front-End",
      "Back-End",
    ],
  },
  {
    href: "https://www.mariamorales.dev/testing/frontend/2022/04/22/front-end-testing.html",
    title: "Front-End Testing Best Practices",
    tags: ["Summary", "Front-End", "Testing", "Engineering"],
  },
  {
    href: "https://gist.github.com/maremarismaria/032ee9251eeda513d0c81843891bc182",
    title: "Triggering Custom Events with Web Storage API & TypeScript",
    tags: ["Util", "TypeScript", "Web Storage API", "Browser", "Listeners", "Auth", "Session"],
  },
  {
    href: "https://codesandbox.io/s/poc-multi-react-rnd-z-index-8tn89?file=/src/App.tsx",
    title: "PoC with React, React-RND (Drag & Drop) and N resizable containers",
    tags: ["PoC", "React", "TypeScript", "State", "Drag & Drop ", "Resizables", "z-index"],
  },
  {
    href: "https://codesandbox.io/s/49iuf?file=/src/components/App/App.tsx",
    title: "Playing with bulbs: dark theme with React, dispatchers & hooks",
    tags: [
      "React",
      "TypeScript",
      "useState",
      "Hooks",
      "Dispatch",
      "SetStateAction",
      "FunctionComponent",
      "styled-components",
      "Dark Theme",
    ],
  },
  {
    href: "https://gist.github.com/maremarismaria/cd736535fd2279fd3741a18707b93d8f",
    title:
      "Animating a bar made with SVG: how to deal with reactivity, React refs & SVG 'defs' elements",
    tags: [
      "React",
      "Animation",
      "HTML",
      "SVG",
      "defs",
      "TypeScript",
      "State",
      "componentDidUpdate",
      "React.Component",
      "MutableRefObject",
      "Refs",
      "linear-gradient",
    ],
  },
  {
    href: "https://codesandbox.io/s/ykshx?file=/src/App.tsxf",
    title: "Triggering custom actions with React, contexts & reducers",
    tags: [
      "React",
      "TypeScript",
      "createContext",
      "useReducer",
      "Provider",
      "Dispatch",
      "State",
    ],
  },
  {
    href: "https://codepen.io/maremarismaria/pen/oNgjrOw",
    title: "Golden Spiral with JavaScript Canvas",
    tags: [
      "Illustration",
      "JavaScript",
      "Canvas",
      "getContext",
      "2D",
      "Golden Spiral",
      "Phi",
      "Maths",
    ],
  },
  {
    href: "https://codepen.io/maremarismaria/pen/QWZdOLb",
    title: "Optical Illusion with SVG Animations (SMIL)",
    tags: ["WIP", "Illustration", "SVG", "Animation", "SMIL", "Trigonometry", "Optical Illusion"],
  },
  {
    href: "https://codepen.io/maremarismaria/pen/ExegGaL",
    title: "CSS 3D illustration",
    tags: [
      "Illustration",
      "CSS",
      "3D",
      "Geometry",
      "Position",
      "Pseudo-elements",
      "Gradients",
      "Filter",
      "z-index",
      "transform",
      "transform-style",
      "preserve-3d",
    ],
  },
  {
    href: "https://github.com/maremarismaria/country-picker",
    title: "Country Picker Component with Nunjucks, SCSS, JavaScript & Webpack",
    tags: [
      "Nunjucks",
      "JavaScript",
      "ES6",
      "Webpack",
      "Component",
      "Templating",
      "Fragments",
      "Assets",
      "JSON",
      "DOMContentLoaded",
      "HtmlWebpackPlugin",
      "Babel",
    ],
  },
  {
    href: "https://codepen.io/maremarismaria/pen/jOyLKqr",
    title: "Collapsible with SCSS and input checkbox (No JavaScript)",
    tags: ["Util", "SCSS", "Nesting", "Input", "Checkbox", "Display", "Toggle"],
  },
  {
    href: "https://codepen.io/maremarismaria/pen/KKxqrQR",
    title: "Pixelated letter with linear-gradient in SCSS",
    tags: ["Util", "SCSS", "Nesting", "Position", "nth-child", "linear-gradient", "Math"],
  },
  {
    href: "https://codepen.io/maremarismaria/pen/poNwMvV",
    title: "Loading Dots in SCSS",
    tags: ["Util", "SCSS", "Pseudo-elements", "@keyframes", "Content", "Animation"],
  },
  {
    href: "https://codepen.io/maremarismaria/pen/eYzJJYq",
    title: "Ribbon in SCSS",
    tags: ["Util", "SCSS", "Pseudo-elements", "Position", "Calc"],
  },
  {
    href: "https://codepen.io/maremarismaria/pen/mdJWGwm",
    title: "Typewriter Effect in CSS",
    tags: ["Util", "CSS", "Animation", "@keyframes", "Width", "caret"],
  },
  {
    href: "https://codepen.io/maremarismaria/pen/wvwVBaa",
    title: "Nokia 5300 in CSS",
    tags: [
      "Illustration",
      "CSS",
      "Nokia",
      "Position",
      "Custom properties",
      "Calc",
      "Pseudo-elements",
    ],
  },
  {
    href: "https://codepen.io/maremarismaria/pen/abzmomW",
    title: "Pixel Baby Yoda in CSS",
    tags: ["Illustration", "CSS", "Position", "Custom properties", "Calc", "Pseudo-elements"],
  },
  {
    href: "https://codepen.io/maremarismaria/pen/XQJaxz",
    title: "Morty Smith in CSS",
    tags: [
      "Illustration",
      "CSS",
      "Position",
      "Custom properties",
      "Calc",
      "Pseudo-elements",
      "Hover",
    ],
  },
  {
    href: "https://codepen.io/maremarismaria/pen/povjXbx",
    title: "Mario Underwater in CSS",
    tags: [
      "Illustration",
      "CSS",
      "Position",
      "Custom properties",
      "Calc",
      "Pseudo-elements",
      "Hover",
    ],
  },
  {
    href: "https://gist.github.com/maremarismaria/f7b268cb8bc3b35ef1bd937bcbbfbd86",
    title: "Introduction to SVG",
    tags: ["WIP", "Summary", "Introduction", "HTML", "SVG", "React", "SVG Component"],
  },
]

export default articlesList